### ISSUE TITLE
Error on getting started

### ISSUE THREAD

**Issue by AbenaAmo13** [koffilabs/material-toys#1]
Hi, 

When I am trying to set up a new project with this library, I am getting the following errors:

```
  react.development.js:1476 Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
  1. You might have mismatching versions of React and the renderer (such as React DOM)
  2. You might be breaking the Rules of Hooks
  3. You might have more than one copy of React in the same app
  See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
      at resolveDispatcher (react.development.js:1476:1)
      at useContext (react.development.js:1484:1)
      at Button (Button.tsx:20:1)
      at renderWithHooks (react-dom.development.js:16305:1)
      at mountIndeterminateComponent (react-dom.development.js:20074:1)
      at beginWork (react-dom.development.js:21587:1)
      at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
      at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
      at invokeGuardedCallback (react-dom.development.js:4277:1)
      at beginWork$1 (react-dom.development.js:27451:1)
  ```

**Comment by nicrizzo** [comment]
Hi,
could you give me some more details or the steps to reproduce the error?
Thank you very much!

**Comment by AbenaAmo13** [comment]
1. I ran `npm install material-toys/react`
2. I pasted the example code, into the App.js file in a blank react project: 

```
import { MT, Button} from "@material-toys/react";
function App() {
  return (
      <MT>
        <Button>Hello World!</Button>
      </MT>
  );
}
export default App;
```
3. I got the following error: `Invalid hooks call`
<img width="1156" alt="Screenshot 2023-03-27 at 17 35 30" src="https://user-images.githubusercontent.com/60615703/228006444-1904b170-0dd1-4692-b977-2e6ee020551e.png">

**Comment by nicrizzo-koffilabs** [comment]
Sorry,
it does not work with react 18 yet.
If you downgrade to react and react-dom 17.02 (change your package json and relaunch npm install), it should work with this App.js:

import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';

const root = ReactDOM.render(<React.StrictMode>
  <App />
</React.StrictMode>, document.getElementById('root'));

Thank you very much,
    Nicola

**Comment by nicrizzo** [comment]
fixed, now MT just works with create react app
